List<Map> company = [
  {
    'logo' : 'assets/start1.png',
    'name' : 'Ola',
    'description' : 'Ola Cabs offers to book cabs nearby your location for best fares. For best taxi service at lowest fares, say Ola!',
    'valuation' : 'Rs. 5.8Cr',
    'target' : 'Rs. 1.2Cr',
    'investors' : '347',
    'image' : 'assets/fun1.png',
    'location' : 'Cork, Ireland',
    'website' : 'https://www.olacabs.com/',
    'company_number' : '685489',
    'incorporation_date' : '7 Jan 2021',
    'type' : 'equity',
    'equity' : '11.11%',
    'share_price' : 'Rs.20.52',
    'tax' : 'EIS'
  },
  {
    'logo' : 'assets/start2.png',
    'name' : 'Swiggy',
    'description' : 'Order food online from restaurants and get it delivered.',
    'valuation' : 'Rs. 1Cr',
    'target' : 'Rs. 5Lac',
    'investors' : '200',
    'image' : 'assets/fun2.jpg',
    'location' : 'Newark, United Kingdom',
    'website' : 'https://www.swiggy.com/',
    'company_number' : '12286089',
    'incorporation_date' : '6 Oct 2019',
    'type' : 'equity',
    'equity' : '14.48%',
    'share_price' : 'Rs.15.33',
    'tax' : 'EIS'
  },
  {
    'logo' : 'assets/start3.png',
    'name' : 'Google Pay',
    'description' : 'Google Pay is a simple, secure, and seamless way to pay and save, giving you helpful ways to do more with your money: - Pay at your favorite places.!',
    'valuation' : 'Rs. 10Lac',
    'target' : 'Rs. 3.5Lac',
    'investors' : '45',
    'image' : 'assets/fun3.jpg',
    'location' : 'Dorchester, United Kingdom',
    'website' : 'https://pay.google.com/gp/w/u/0/home/activity?sctid=1848482178175043',
    'company_number' : '07931505',
    'incorporation_date' : '1 Feb 2012',
    'type' : 'equity',
    'equity' : '7.72%',
    'share_price' : 'Rs.2.28',
    'tax' : 'EIS'
  },
];